sudo: false
dist: xenial
language: c

matrix:
   include:
      - os: linux
        addons:
           apt:
              sources:
                 - ubuntu-toolchain-r-test
              packages:
                 - gfortran-7
                 - cmake
        env:
           - FC='gfortran-7'
      - os: linux
        addons:
           apt:
              sources:
                 - ubuntu-toolchain-r-test
              packages:
                 - gfortran-8
                 - cmake
        env:
           - FC='gfortran-8'
      - os: linux
        addons:
           apt:
              sources:
                 - ubuntu-toolchain-r-test
              packages:
                 - gfortran-9
                 - cmake
        env:
           - FC='gfortran-9'
      - os: osx
        osx_image: xcode9.4
        env:
           - FC='gfortran-7'
           - BREW='gcc@7'
           - BREW_UP='cmake'
           - CACHE_NAME=osx-gcc7
      - os: osx
        osx_image: xcode10.3
        env:
           - FC='gfortran-8'
           - BREW='gcc@8'
           - BREW_UP='cmake'
           - CACHE_NAME=osx-gcc8
      - os: osx
        osx_image: xcode11.2
        env:
           - FC='gfortran-9'
           - BREW='gcc@9'
           - BREW_UP='cmake'
           - CACHE_NAME=osx-gcc9

before_install:
   - |
      if [ $TRAVIS_OS_NAME == osx ] ; then
         brew install ${BREW} make || exit 1
         brew upgrade ${BREW_UP} || exit 1
      fi

install:
  # Set the ${CXX} variable properly
#  - export CXX=${COMPILER}
#  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"

  # Travis machines have 2 cores
  - JOBS=2

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.14.5
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

before_script:
   # First get pFUnit
   - cd ${HOME}
   - git clone https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git

   # Now build pFUnit
   - cd ${HOME}/pFUnit
   - mkdir build-serial
   - cd build-serial
   - cmake .. -DCMAKE_Fortran_COMPILER=${FC} -DCMAKE_INSTALL_PREFIX=$HOME/Software/pFUnit -DSKIP_MPI=YES -DSKIP_OPENMP=YES
   - make -j4 install

   # Now build fArgParse
   - cd ${TRAVIS_BUILD_DIR}
   - mkdir build
   - cd build
   - cmake .. -DCMAKE_Fortran_COMPILER=${FC} -DCMAKE_INSTALL_PREFIX=$HOME/Software/fArgParse -DCMAKE_PREFIX_PATH=$HOME/Software/pFUnit -DCMAKE_BUILD_TYPE=Debug

script:
   # Build and install
   - make -j install
   # Test
   - make -j tests

notifications:
   email:
      recipients:
         - matthew.thompson@nasa.gov
         - thomas.l.clune@nasa.gov
         
