name: CI Tests

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        compiler: [gfortran-9, gfortran-10]

    env:
      FC: ${{ matrix.compiler }}
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_TYPE: en_US.UTF-8

    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    steps:
      - name: Compiler Versions
        run: |
          ${FC} --version
          cmake --version
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build GFE Prereqs
        run: |
          bash ./tools/travis-install-gfe.bash
      - name: Build fArgParse
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=${HOME}/Software/fArgParse -DCMAKE_PREFIX_PATH=${HOME}/Software/GFE
          make -j$(nproc)
      - name: Build Tests
        run: |
          cd build
          make -j$(nproc) tests
      - name: Run Tests
        run: |
          cd build
          ctest -j1 --output-on-failure --repeat until-pass:4
